SET SESSION group_concat_max_len = 99999999999999999;
sELECT "GENDER" as "COL", GENDER, GROUP_CONCAT(PERSON_ID SEPARATOR ',') AS PERSON_IDS
FROM CALCULATED_PATIENT_DATA
GROUP BY GENDER

union ALL

SELECT "RACE" as "COL", RACE, GROUP_CONCAT(PERSON_ID SEPARATOR ',') AS PERSON_IDS
FROM CALCULATED_PATIENT_DATA
GROUP BY "RACE", RACE

