UPDATE CALCULATED_DX_DATA AS D
SET age_at_dx = (
  SELECT CAST(
    (julianday(MIN(D2."DATE")) - julianday(P.DATE_OF_BIRTH)) / 365.2425
    AS INTEGER
  )
  FROM CALCULATED_DX_DATA AS D2
  JOIN CALCULATED_PATIENT_DATA AS P
    ON P.PERSON_ID = D2.PERSON_ID
  WHERE D2.PERSON_ID = D.PERSON_ID
);