SELECT DISTINCT(t1.CONDITION_CONCEPT_ID),
                COALESCE(s.concept_name, 'unknown') AS concept_name,
                CONDITION_START_DATETIME
   FROM omop.DIAGNOSIS_MELANOMA_OUTPT_VW t1
LEFT JOIN lookup.SNOMED_CODES s ON t1.CONDITION_CONCEPT_ID = s.concept_id
   JOIN
    lookup.icd_codes i ON left(i.CODE, 3) = left(SUBSTRING_INDEX(t1.CONDITION_SOURCE_VALUE, ':', -1), 3)
WHERE t1.PERSON_ID = 'REDACTED_PERSON_ID'

SELECT DATE,
       CANCER
from lookup.CALCULATED_PT_ICD_CODES icd, omop.DIAGNOSIS_MELANOMA_OUTPT_VW d
WHERE icd.PERSON_ID = d.PERSON_ID
  AND icd.CANCER = 'M'
  AND d.PERSON_ID = 'REDACTED_PERSON_ID'
